### ISSUE TITLE
shiki:vscode is not defined

### ISSUE THREAD

**Issue by moshuiyan** [kode-team/easylogic.studio#183]
I run this project local ,and find something lose .   Open the [website](https://editor.easylogic.studio/), there has the same problem.
![image](https://user-images.githubusercontent.com/73340105/200216081-3e2b293b-684b-4ea1-86b4-2791be31a4fc.png)
![image](https://user-images.githubusercontent.com/73340105/200216151-9e8172c8-2773-4f46-9fb4-8a814c465fd9.png)

What's the 'vscode' in "shiki"  ?

**Comment by easylogic** [comment]
hi @moshuiyan  

thanks for your reporting.

This is shiki bugs. 

refer to https://github.com/shikijs/shiki/issues/338

I will fix it and let you know after

**Comment by easylogic** [comment]
This is fixed.
